name: Healthomics Workflows Validator

on:
  push:
    paths:
      - workflows/*/input_templates/*.json
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  validate-input-templates:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install boto3

    - name: Validate input templates
      run: python scripts/healthomics_wf/utils/validate_input_templates.py

  validate-docker-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install boto3

    - name: Validate docker images
      run: python scripts/healthomics_wf/utils/validate_globals_docker_images.py workflows
