name: Healthomics Workflows Validator

on:
  push:
    paths:
      - workflows/*/input_templates/*.json
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: us-east-1
  AWS_ROLE: arn:aws:iam::337532070941:role/google-aws-sync-aws-role

jobs:
  validate-input-templates:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install boto3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}

    - name: validate input templates
      run: python .github/utils/validate_input_templates.py
