name: Healthomics Workflows Validator

on:
  push:
    paths:
      - workflows/*/input_templates/*.json
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  validate-input-templates:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install boto3

    - name: validate input templates
      run: python .github/utils/validate_input_templates.py
